language: java

env:
  global:
    - ecure: "Th01qXCbTPfnXwsXSb+17CGHSSH8DNvzdiTT2E68RG9i9DY9ClEkQhKzwNJx\n5BSVxev4p+uS5rS1tdMuD1Smg2CdDFNHoqHDZbBuMQ/ZPyNMPjNGxXNyZPZW\nq7fl+kDDU7oAil/HRuEtHmHdyzMEUGt8NDaSFchSDKJ4rI3+g5M="

branches:
  except:
    - v3.0-dist
    - master-dist

before_script: 
  - ant test -Djshint.failbuild=true

script:
  - ant

after_success:
  - ./build/post_build.sh
