language: java

env:
  global:
    - secure: "rmN2TEeTxkLgdDPEK3pzaP4nLQxikAzu1wXlChlWYZFz8gb1rr5BJHqZAQhnAqtPA0209sRBa20r9LbBRNY87mnODl7BbOb1o/i400NWxKHdQHpMa0LRZRJz/GWu3X6+ny4l9hB4f6KOnL8UAbFEWPxBnZI7KD30fLNGVxgN/xo="
    - POST_BUILD=true

script:
  - ant test -Djshint.failbuild=true && ant && ./build/post_build.sh

notifications:
  irc:
  - "chat.freenode.net#wet-boew"
