language: java

env:
  global:
    - secure: "lmxcwdqRU0enOwOQTnzhLxc2aKBGdOFc+SEPrOnCgywyDjIjl6QSdS3+hXWs\nKit6mASnofUn52Zlu+8ahdbHmlELHQVp0ukzCKgOBnxGXE1fomzXSAAiBMZH\naTj0fUh5WQWDKw5pt6If7vGFfPkMfPcW5yc8M1jpcqVFJB2ZS+g="

branches:
  except:
    - v3.0-dist
    - master-dist

before_script: 
  - ant test -Djshint.failbuild=true

script:
  - ant

after_success:
  - ./build/post_build.sh
