language: generic
dist: trusty
sudo: required

env:
  global:
    - TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"

before_install:
  - echo "machine github.com login $GH_TOKEN" >> ~/.netrc
  - env | grep  'TRAVIS\|CI\|SAUCE\|GIT\|REPO\|BRANCH' | sed -e 's/=\(.*\)/="\1"/g' >> script/docker/env >> script/docker/env
  - cat script/docker/env
  - shopt -s expand_aliases
  - source script/docker/activate
  - npm --version

install:
  - npm install --quiet

script:
  - npm run-script travis_script

after_success:
  - npm run-script travis_after_success

notifications:
  irc:
  - "chat.freenode.net#wet-boew"
