language: node_js
node_js:
  - "6"

sudo: false

env:
  global:
    - TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"

before_install:
  - echo "machine github.com login $GH_TOKEN" >> ~/.netrc
  - rvm install 2.2.2

install:
  - ./script/setup
  - gem install rake html-proofer

script:
  - npm run-script travis_script

after_success:
  - npm run-script travis_after_success

notifications:
  irc:
  - "chat.freenode.net#wet-boew"
